// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sistema_de_Verificación_IMEI.Data;

#nullable disable

namespace Sistema_de_Verificación_IMEI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260630140459_AddHistorialEscaneos")]
    partial class AddHistorialEscaneos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecharegistro")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("imei");

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer")
                        .HasColumnName("personaid");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_dispositivos_activo")
                        .HasFilter("activo = true");

                    b.HasIndex("IMEI")
                        .IsUnique()
                        .HasDatabaseName("ix_dispositivos_imei");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("ix_dispositivos_personaid");

                    b.ToTable("dispositivos", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.HistorialEscaneo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalles");

                    b.Property<DateTime>("FechaEscaneo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_escaneo")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IMEI")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("imei");

                    b.Property<bool>("Resultado")
                        .HasColumnType("boolean")
                        .HasColumnName("resultado");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("historial_escaneos", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresaid");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechacreacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_personas_empresaid");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("ix_personas_identificacion");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("integer")
                        .HasColumnName("empresa_id");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Usuario")
                        .HasColumnName("rol");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .HasDatabaseName("ix_usuarios_activo")
                        .HasFilter("activo = true");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_usuarios_empresa_id");

                    b.HasIndex("Rol")
                        .HasDatabaseName("ix_usuarios_rol");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Dispositivo", b =>
                {
                    b.HasOne("Sistema_de_Verificación_IMEI.Models.Persona", "Persona")
                        .WithMany("Dispositivos")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispositivos_persona");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.HistorialEscaneo", b =>
                {
                    b.HasOne("Sistema_de_Verificación_IMEI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_historial_escaneos_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Persona", b =>
                {
                    b.HasOne("Sistema_de_Verificación_IMEI.Models.Empresa", "Empresa")
                        .WithMany("Personas")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_personas_empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Usuario", b =>
                {
                    b.HasOne("Sistema_de_Verificación_IMEI.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_usuarios_empresa");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Empresa", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Sistema_de_Verificación_IMEI.Models.Persona", b =>
                {
                    b.Navigation("Dispositivos");
                });
#pragma warning restore 612, 618
        }
    }
}
